version: 2.1

jobs:
  gcc-10:
    docker:
      - image: mattflow/cbmp-gcc:10
    steps:
      - checkout
      - run: make test-full
  gcc-9:
    docker:
      - image: mattflow/cbmp-gcc:9
    steps:
      - checkout
      - run: make test-full
  gcc-8:
    docker:
      - image: mattflow/cbmp-gcc:8
    steps:
      - checkout
      - run: make test-full
  clang-9:
    docker:
      - image: mattflow/cbmp-clang:9
    steps:
      - checkout
      - run: make test-full
  clang-8:
    docker:
      - image: mattflow/cbmp-clang:8
    steps:
      - checkout
      - run: make test-full
  clang-6:
    docker:
      - image: mattflow/cbmp-clang:6
    steps:
      - checkout
      - run: make test-full

workflows:
  test-gcc:
    jobs:
      - gcc-10
      - gcc-9
      - gcc-8
  test-clang:
    jobs:
      - clang-9
      - clang-8
      - clang-6